from setuptools import setup, find_packages

setup(
    name="radionets",
    version="0.0.5",
    description="Imaging radio interferometric data with neural networks",
    url="https://github.com/Kevin2/radionets",
    author="Kevin Schmidt, Felix Geyer, Kevin Laudamus",
    author_email="kevin3.schmidt@tu-dortmund.de",
    license="MIT",
    packages=find_packages(),
    install_requires=[
        "torch==1.5",
        "torchvision==0.6",
        "numpy",
        "astropy",
        "tqdm",
        "click",
        "geos",
        "shapely",
        "proj",
        "cartopy",
        "ipython",
        "jupyter",
        "jupytext",
        "h5py",
        "scikit-image",
        "pandas",
        "requests",
        "toml",
    ],
    setup_requires=["pytest-runner"],
    tests_require=["pytest"],
    zip_safe=False,
    entry_points={
        "console_scripts": [
            "radionets_simulations = simulations.scripts.simulate_images:main",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.7",
        'Programming Language :: Python :: 3.8',
        "Programming Language :: Python :: 3 :: Only",
        "Topic :: Scientific/Engineering :: Astronomy",
        "Topic :: Scientific/Engineering :: Physics",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
)
