# This is a TOML document.

title = "Train configuration"

[mode]
quiet = true
telegram_logger = false
gpu = true

[paths]
data_path = "/net/big-tank/POOL/projects/radio/simulations/jet_components/220527_n10000_s256"
# model_path = "/net/big-tank/POOL/projects/radio/models/jet/220527_unet_jet_segmentation_c7.model"
model_path = "/net/big-tank/POOL/users/apoggenpohl/radionets/models/220527_unet_jet_segmentation_c7.model"
pre_model = "none"
norm_path = "none"

[general]
fourier = false
amp_phase = false
source_list = false
arch_name = "UNet_jet"
loss_func = "jet_seg"
num_epochs = 30
inspection = false
output_format = "pdf"

[hypers]
batch_size = 8
lr = 1e-04

[param_scheduling]
use = true
lr_start = 1e-3
lr_max = 7e-4
lr_stop = 1e-4
