from pathlib import Path

import lightning as L
import rich_click as click
from rich.pretty import pretty_repr

from radionets.core.callbacks import Callbacks
from radionets.core.logging import Loggers, _setup_logger
from radionets.io import TrainConfig
from radionets.training import TrainModule
from radionets.utils.carbon_tracking import CarbonTracker

LOGGER = _setup_logger(namespace=__name__)


@click.command()
@click.argument("config_path", type=click.Path(exists=True, dir_okay=False))
@click.option("--premodel", "-p", type=click.Path(exists=True, dir_okay=False))
def main(config_path, premodel=None):
    """Starts the radionets training process with
    options specified in configuration file.

    Parameters
    ----------
    configuration_path : str
        Path to the configuration toml file.
    mode : str, optional
        Operation mode, can be one of {'train', 'test', 'predict'}.
        Default: 'train'
    """
    if not isinstance(config_path, Path):
        config_path = Path(config_path)

    train_config = TrainConfig.from_toml(config_path)

    LOGGER.info(pretty_repr(train_config))

    if premodel:
        # if the premodel cli option is used, overwrite config path
        train_config.paths.checkpoint = premodel

    data_module = train_config.dataloader.module(
        data_dir=train_config.paths.data_path,
        **train_config.dataloader.model_dump(),
    )  # ty:ignore[call-non-callable]

    # Dumping train_config to a dict here results in nicer
    # formatting in hparams.yaml files generated by lightning
    train_module = TrainModule(train_config.model_dump(), data_module.train_length)

    loggers = Loggers.get_loggers(train_config)
    callbacks = Callbacks.get_callbacks(train_config)

    # with rich_training_layout(train_config, callbacks) as layout_callbacks:
    trainer = L.Trainer(
        limit_train_batches=data_module.train_length
        // train_config.dataloader.batch_size
        if data_module.train_length
        else train_config.dataloader.batch_size,
        limit_val_batches=data_module.valid_length // train_config.dataloader.batch_size
        if data_module.valid_length
        else train_config.dataloader.batch_size,
        limit_test_batches=data_module.test_length // train_config.dataloader.batch_size
        if data_module.test_length
        else train_config.dataloader.batch_size,
        max_epochs=train_config.training.num_epochs,
        callbacks=callbacks,
        logger=loggers,
        log_every_n_steps=train_config.dataloader.batch_size,
        devices=train_config.devices.num_devices,
        accelerator=train_config.devices.accelerator,
        precision=train_config.devices.precision,
        strategy=train_config.devices.deepspeed
        if train_config.devices.deepspeed
        else train_config.devices.strategy,
    )

    trainer.radionets_task = "training"

    # let mlflow callback stop the tracker
    stop_inside_scope = train_config.logging.mlflow

    with CarbonTracker(
        train_config=train_config, stop_inside_scope=stop_inside_scope
    ) as tracker:
        trainer.carbontracker = tracker
        trainer.fit(model=train_module, datamodule=data_module)


if __name__ == "__main__":
    main()
