# This is a TOML document.

title = "Train configuration"

[mode]
quiet = true
gpu = false

[logging]
comet_ml = true
project_name = "VLA"
plot_n_epochs = 2
scale = true

[paths]
data_path = "./example_data/"
model_path = "./build/example_model/example.model"
pre_model = "none"
norm_path = "none"

[general]
fourier = true
amp_phase = true
source_list = false
arch_name = "filter_deep"
loss_func = "splitted_L1"
num_epochs = 5
inspection = true
output_format = "png"
switch_loss = false
when_switch = 25

[hypers]
batch_size = 100
lr = 1e-3

[param_scheduling]
use = true
lr_start = 7e-2
lr_max = 3e-1
lr_stop = 5e-2
lr_ratio = 0.25
