# This is a TOML document.

title = "Simulation configuration"

[mode]
quiet = true

[paths]
data_path = "./example_data/"
data_format = "h5"

[gaussians]
simulate = true
num_components = [4, 10]

[point_sources]
simulate = false
add_extended = false

[image_options]
bundles_train = 5
bundles_valid = 1
bundles_test = 1
bundle_size = 200
img_size = 63
noise = false
noise_level = 5
white_noise = false
mean_real = 0.85
std_real = 0.0425
mean_imag = 0.2
std_imag = 0.01

[sampling_options]
fourier = true
real_imag = false
amp_phase = true
antenna_config = "vlba"
specific_mask = true
lon = -80
lat = 50
steps = 50
keep_fft_files = true
source_list = false
compressed = false
interpolation = false
multi_channel = false
bandwidths = 1
