# This is a TOML document.

title = "Simulation configuration"

[mode]
quiet = true

[paths]
data_path = "./benchmark_data/"
data_format = "h5"

[mnist]
simulate = false
resource = "../../resources/mnist.pkl.gz"

[gaussians]
simulate = true
pointsources = false
num_pointsources = 10
pointlike_gaussians = false
num_pointlike_gaussians = 5
extended_gaussians = true
num_components = [4, 10]

[image_options]
bundles_train = 0
bundles_valid = 0
bundles_test = 1
bundle_size = 20
img_size = 63
noise = false
noise_level = 5

[sampling_options]
fourier = true
real_imag = false
amp_phase = true
antenna_config = "vlba"
specific_mask = false 
lon = -80
lat = 50
steps = 50
keep_fft_files = true
source_list = false
compressed = false
interpolation = true
multi_channel = false
