# This is a TOML document.

title = "Simulation configuration"

[mode]
quiet = true

[paths]
data_path = "./example_data/fourier_real"
data_format = "h5"

[mnist]
simulate = false
resource = "../../resources/mnist.pkl.gz"

[gaussians]
simulate = true
num_components = [4, 10]

[point_sources]
simulate = false
add_extended = false

[image_options]
bundles_train = 1
bundles_valid = 1
bundles_test = 1
bundle_size = 10
img_size = 63
noise = false
noise_level = 5

[sampling_options]
fourier = true
real_imag = true
amp_phase = false
antenna_config = "vlba"
specific_mask = true
lon = -80
lat = 50
steps = 50
keep_fft_files = true
source_list = false
compressed = false
interpolation = false
multi_channel = false
