name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

env:
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes
  GITHUB_PR_NUMBER: ${{ github.event.number }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.pull_request.labels.*.name, 'skip-ci') == false
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.11"
            install-method: mamba

          - os: ubuntu-latest
            python-version: "3.12"
            install-method: mamba
            extra-args: ["codecov"]

    defaults:
      run:
        # We need login shells (-l) for micromamba to work.
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare mamba installation
        if: matrix.install-method == 'mamba' &&  contains(github.event.pull_request.labels.*.name, 'documentation-only') == false
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          # setup correct python version
          sed -i -e "s/- python.*/- python=$PYTHON_VERSION/g" environment-dev.yml

      - name: mamba setup
        if: matrix.install-method == 'mamba' &&  contains(github.event.pull_request.labels.*.name, 'documentation-only') == false
        uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          environment-file: environment-dev.yml
          cache-downloads: true

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: false

      - name: Install dependencies
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          python --version
          uv pip install --upgrade pip
          uv pip install --group tests -e .
          uv pip freeze
          uv pip list

      - name: List installed package versions (conda)
        if: matrix.environment-type == 'mamba'
        run: micromamba list

      - name: Tests
        run: |
          pytest -vv --cov --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

      - name: Upload coverage to Codecov
        if: contains(matrix.extra-args, 'codecov') && contains(github.event.pull_request.labels.*.name, 'documentation-only') == false
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage

      - name: Report Test Results
        if: contains(matrix.extra-args, 'codecov') && contains(github.event.pull_request.labels.*.name, 'documentation-only') == false
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results

  docs:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'skip-ci') == false
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.11"

      - name: Install doc dependencies
        run: |
          sudo apt update --yes && sudo apt install --yes git
          uv pip install --system . -U pip towncrier
          uv pip install --system . --group docs -e .
          git describe --tags

      - name: Build docs
        run: make -C docs html

      - name: Produce Changelog
        run: |
          towncrier build --yes --version==0.0.0
