name: Build and publish radionets

on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hynek/build-and-inspect-python-package@v2
        with:
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2.18.0
        with:
          name: Packages-distlong-${{ github.job }}
          path: dist/*

      - name: Check metadata
        run: uvx twine check ./dist/*

  publishtrusted:
    needs: [ dist ]
    environment: pypi
    permissions:
      id-token: write
      attestations: write
      contents: read
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: Packages
          path: dist

      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "./dist/*"

      - uses: pypa/gh-action-pypi-publish@release/v1
